# Generated by Django 3.2.7 on 2021-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
