version: "3.3"
services:
  projectnginx:
    image: nginx:1.21.1
    networks:
      - project
    volumes:
      - /home/ubuntu/project_config/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/buscp.org/fullchain.pem:/etc/letsencrypt/live/buscp.org/fullchain.pem
      - /etc/letsencrypt/live/buscp.org/privkey.pem:/etc/letsencrypt/live/buscp.org/privkey.pem
      - static-volume-project:/data/static
      - media-volume-project:/data/media
      - /home/ubuntu/PROJECT_HOME_BUILD:/data/build
      - /home/ubuntu/SOTONGORI_BUILD:/data/build/sotong
      - /var/www/certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - project_home
  
  projectmariadb:
    image: mariadb:10.5
    networks:
      - project
    volumes:
      - /home/ubuntu/project_database:/var/lib/mysql
    secrets:
      - PROJECT_MARIADB_ROOT_PASSWORD
      - PROJECT_MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: projectdb
      MARIADB_USER: project
      MARIADB_PASSWORD_FILE: /run/secrets/PROJECT_MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/PROJECT_MARIADB_ROOT_PASSWORD
    
  project_home:
    image: project_home:0.4
    secrets:
      - PROJECT_MARIADB_ROOT_PASSWORD
      - PROJECT_MARIADB_PASSWORD
    networks:
      - project
    volumes:
      - /home/ubuntu/project_server:/home/ubuntu/project_server
      - static-volume-project:/home/ubuntu/project_server/staticroot
      - media-volume-project:/home/ubuntu/project_server/media
    depends_on: 
      - projectmariadb
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["bash", "-c"]
    command: 
      - |
        python manage.py collectstatic --noinput --settings=config.settings.prod
        python manage.py makemigrations --noinput --settings=config.settings.prod
        python manage.py migrate --noinput --settings=config.settings.prod
        gunicorn config.wsgi --bind 0.0.0.0:8000 --workers=3 --thread=3 --timeout=90 \
        --env DJANGO_SETTINGS_MODULE=config.settings.prod
# python manage.py runserver 0.0.0.0:8000 --settings=config.settings.prod

  project_apply:
    image: project_home:0.4
    secrets:
      - PROJECT_MARIADB_ROOT_PASSWORD
      - PROJECT_MARIADB_PASSWORD
    networks:
      - project
    volumes:
      - /home/ubuntu/project_server:/home/ubuntu/project_server
      - static-volume-project:/home/ubuntu/project_server/staticroot
      - media-volume-project:/home/ubuntu/project_server/media
    depends_on: 
      - projectmariadb
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["bash", "-c"]
    command: 
      - |
        python manage.py collectstatic --noinput --settings=config.settings.prod
        python manage.py makemigrations --noinput --settings=config.settings.prod
        python manage.py migrate --noinput --settings=config.settings.prod
        gunicorn config.wsgi --bind 0.0.0.0:8080 --workers=3 --thread=3 --timeout=90 \
        --env DJANGO_SETTINGS_MODULE=config.settings.prod

networks:
  project:

volumes:
  static-volume-project:
  media-volume-project:

secrets:
  PROJECT_MARIADB_PASSWORD:
    external: true
  PROJECT_MARIADB_ROOT_PASSWORD:
    external: true