version: "3.3"
services:
  project_home:
    image: project_home:1.3
    volumes:
      - /home/ubuntu/project_server:/home/ubuntu/project_server
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["bash", "-c"]
    command: 
      - |
        python manage.py makemigrations --noinput --settings=config.settings.local
        python manage.py migrate --noinput --settings=config.settings.local
        python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local

