# Generated by Django 3.2.7 on 2021-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
