# Generated by Django 3.2.7 on 2021-10-09 11:57

import activity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='activity_thumbnail/')),
            ],
            options={
                'verbose_name': '활동 내역',
                'verbose_name_plural': '활동 내역 모음',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_detail')),
                ('activity_file', models.FileField(blank=True, null=True, upload_to=activity.models.get_file_path, verbose_name='활동파일')),
                ('description', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
            options={
                'verbose_name': '활동 세부사항',
                'verbose_name_plural': '활동 세부 모음',
            },
        ),
        migrations.CreateModel(
            name='ActivityDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_detail')),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, null=True)),
                ('activity_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitydetail')),
            ],
            options={
                'verbose_name': '활동 사진',
                'verbose_name_plural': '활동 사진 모음',
                'ordering': ['order'],
            },
        ),
    ]
