# Generated by Django 3.2.7 on 2021-09-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydetailimage',
            options={'ordering': ['order'], 'verbose_name': '활동 사진', 'verbose_name_plural': '활동 사진 모음'},
        ),
        migrations.AddField(
            model_name='activitydetailimage',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
