# Generated by Django 3.2.7 on 2021-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activitydetail_activity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetailimage',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
