# Generated by Django 3.2.7 on 2021-11-25 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('birth', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=8)),
            ],
            options={
                'verbose_name': '지원자',
                'verbose_name_plural': '지원자',
                'ordering': ['-apply_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_multichoice', models.BooleanField(default=False)),
                ('can_duplicate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=survey.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=128, null=True, verbose_name='첨부파일명')),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyfile', to='survey.applier')),
            ],
            options={
                'verbose_name': '지원서 첨부파일',
                'verbose_name_plural': '지원서 첨부파일',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '지원/설문',
                'verbose_name_plural': '지원/설문',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_content', models.CharField(blank=True, max_length=128, null=True)),
                ('can_select', models.BooleanField(default=False)),
                ('top_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_question', to='survey.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='applier',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applier', to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='survey.applier')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='survey.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='survey.survey')),
            ],
        ),
    ]
