# Generated by Django 3.2.7 on 2021-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20211127_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='applier',
            name='univ',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
