# Generated by Django 3.2.7 on 2021-12-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_question_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applier',
            old_name='is_picked',
            new_name='first_picked',
        ),
        migrations.AddField(
            model_name='applier',
            name='finaly_picked',
            field=models.BooleanField(default=False, verbose_name='최종 선발 여부'),
        ),
        migrations.AlterField(
            model_name='applier',
            name='is_applied',
            field=models.BooleanField(default=False, verbose_name='지원 여부'),
        ),
        migrations.AlterField(
            model_name='applier',
            name='is_favor',
            field=models.BooleanField(default=False, verbose_name='관심 지원자'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=2000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('applier', models.ManyToManyField(related_name='comment', to='survey.Applier')),
            ],
            options={
                'verbose_name': '지원자',
                'verbose_name_plural': '지원자',
            },
        ),
    ]
