# Generated by Django 3.2.7 on 2021-12-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20211230_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applier',
            name='first_picked',
            field=models.BooleanField(default=False, verbose_name='1차 선발 여부'),
        ),
    ]
