# Generated by Django 3.2.7 on 2021-09-14 07:40

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=boards.models.get_file_path, verbose_name='파일'),
        ),
    ]
