# Generated by Django 3.2.7 on 2021-09-14 08:08

import boards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210914_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_files',
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=boards.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postfile', to='boards.post')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일 모음',
                'ordering': ['-post__created_date'],
            },
        ),
    ]
