# Generated by Django 3.2.7 on 2021-09-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20210914_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글 모음'},
        ),
    ]
